Fix nav bar
WildCodeSchool/2023-03-remote-fr-php-afac-974 pull request #14
Opened 2023-06-13 15:08 UTC by valphi41

2023-06-13 15:19 UTC, Victoria140696 approved these changes

2023-06-13 15:22 UTC, Karabuff approved these changes
J'approuve surtout le logo joli boulot ! xD

2023-06-14 09:00 UTC, jfm-wcs requested changes
petite modification côté bootstrap et c'est ok

2023-06-14 09:00 UTC, jfm-wcs commented on templates/include/_navbar.html.twig
> +		<a class="logo-link justify-content-center col-3 " href="/">
la classe row + la classe container-fluid sur la même div c'est étrange 🧐
En principe on intègre .row dans une .container pour des raisons de padding et margin 😉

2023-06-14 11:57 UTC, Karabuff approved these changes
last one REALLY ? j'espere que tu as fait -u sur ton git push AU CAS OU :D

2023-06-14 12:16 UTC, merged