Us 9.2 user crud
WildCodeSchool/2023-03-remote-fr-php-afac-974 pull request #42
Opened 2023-06-22 12:57 UTC by valphi41

2023-06-22 14:37 UTC, jfm-wcs requested changes
une toute petite remarque parce que je suis comme ça 😛

2023-06-22 14:37 UTC, jfm-wcs commented on templates/admin_user/edit.html.twig
> +        <img src="{{ user.avatar }}" class="card-img-top" alt="...">
hum un `style="width: 18rem;"` ? 🧐

2023-06-22 14:55 UTC, valphi41 commented on templates/admin_user/edit.html.twig
> +        <img src="{{ user.avatar }}" class="card-img-top" alt="...">
C'est pas moi c'est Bootstrap... 🙄

2023-06-23 07:45 UTC, jfm-wcs approved these changes

2023-06-23 07:46 UTC, merged