Us.fix
WildCodeSchool/2023-03-remote-fr-php-afac-974 pull request #60
Opened 2023-07-03 09:39 UTC by Karabuff

2023-07-03 10:09 UTC, valphi41 approved these changes
ça à l'air good ! Jusqu'à la review de JF 😏

2023-07-04 13:12 UTC, jfm-wcs requested changes

2023-07-04 13:12 UTC, jfm-wcs commented on templates/galery/index.html.twig
>                      <div>{{ form_start(form) }}
attention ouverture + fermeture du form

2023-07-04 15:10 UTC, jfm-wcs approved these changes

2023-07-04 15:10 UTC, merged